name: Backend CI (pytest + coverage)

on:
  push:
    paths:
      - "complaint-system/backend/**"
      - ".github/workflows/ci-backend.yml"
  pull_request:
    paths:
      - "complaint-system/backend/**"
      - ".github/workflows/ci-backend.yml"

jobs:
  test-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: complaint-system/backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('complaint-system/backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests with coverage
        env:
          ENV: dev
          JWT_SECRET: test-secret
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=app --cov-report=xml --cov-report=term-missing

      - name: Summarize and enforce coverage
        run: python scripts/ci_backend_coverage.py