name: E2E CI (Playwright)

on:
  push:
    paths:
      - "complaint-system/**"
      - ".github/workflows/ci-e2e.yml"
  pull_request:
    paths:
      - "complaint-system/**"
      - ".github/workflows/ci-e2e.yml"

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Frontend setup
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: complaint-system/frontend/package-lock.json

      - name: Install frontend deps
        working-directory: complaint-system/frontend
        run: npm ci

      # Backend setup
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('complaint-system/backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install backend deps
        working-directory: complaint-system/backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Start backend API
      - name: Launch backend
        working-directory: complaint-system/backend
        env:
          ENV: dev
          JWT_SECRET: test-secret
        run: |
          nohup python -m uvicorn main:app --host 127.0.0.1 --port 8000 --log-level warning &

      # Install Playwright browsers
      - name: Install Playwright
        working-directory: complaint-system/frontend
        run: npx playwright install --with-deps

      # Start frontend dev server
      - name: Launch frontend
        working-directory: complaint-system/frontend
        run: |
          nohup npm run dev -- --host --port 5173 &

      # Wait for services
      - name: Wait for services
        run: |
          for i in {1..60}; do
            if curl -sSf http://127.0.0.1:8000/health >/dev/null; then echo "Backend up"; break; fi; sleep 1;
          done
          for i in {1..60}; do
            if curl -sSf http://127.0.0.1:5173 >/dev/null; then echo "Frontend up"; break; fi; sleep 1;
          done

      # Run Playwright tests
      - name: Run Playwright tests
        working-directory: complaint-system/frontend
        run: npx playwright test --reporter=line

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: complaint-system/frontend/playwright-report