name: Frontend CI (Vitest + coverage)

on:
  workflow_dispatch:

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: complaint-system/frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: complaint-system/frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Unit/Integration tests with coverage (Vitest)
        run: npm run test -- --run --coverage --coverage.provider=v8 --coverage.reporter=json-summary --coverage.reporter=text

      - name: Summarize and enforce coverage
        run: node scripts/ci_frontend_coverage.js