name: Frontend CI (Vitest + coverage)

on:
  push:
    paths:
      - "complaint-system/frontend/**"
      - ".github/workflows/ci-frontend.yml"
  pull_request:
    paths:
      - "complaint-system/frontend/**"
      - ".github/workflows/ci-frontend.yml"

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: complaint-system/frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: complaint-system/frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Unit/Integration tests with coverage (Vitest)
        run: npm run test -- --coverage --run

      - name: Summarize and enforce coverage
        run: node scripts/ci_frontend_coverage.js